language: php
 
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
 
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mkdir sandbox/tmp
  - chmod 0775 sandbox/tmp 
 
script: phpunit